-- MySQL Script generated by MySQL Workbench
-- 11/14/16 19:49:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db-colegio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-colegio` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `db-colegio` ;

-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-DatosMedicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-DatosMedicos` (
  `Codigo-DatosMedicos` INT NOT NULL,
  `Alergias` VARCHAR(45) NOT NULL,
  `Enfermedades que padece` VARCHAR(45) NOT NULL,
  `Tipo Sangre` VARCHAR(45) NOT NULL,
  `Medicamentos` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Codigo-DatosMedicos_UNIQUE` (`Codigo-DatosMedicos` ASC),
  PRIMARY KEY (`Codigo-DatosMedicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-matriculas` (
  `Codigo-Matriculas` INT NOT NULL,
  `Nombre del estudiante` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Fecha de Nacimiento` DATETIME NOT NULL,
  `Identidad` INT NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Jornada` VARCHAR(45) NOT NULL,
  `Correo Electronico` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Codigo-DatosMedicos` INT NOT NULL,
  PRIMARY KEY (`Codigo-Matriculas`),
  UNIQUE INDEX `Codigo-Matriculas_UNIQUE` (`Codigo-Matriculas` ASC),
  INDEX `fk_tbl-matriculas_tbl-DatosMedicos1_idx` (`Codigo-DatosMedicos` ASC),
  CONSTRAINT `fk_tbl-matriculas_tbl-DatosMedicos1`
    FOREIGN KEY (`Codigo-DatosMedicos`)
    REFERENCES `db-colegio`.`tbl-DatosMedicos` (`Codigo-DatosMedicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Encargado` (
  `Codigo-Encargado` INT NOT NULL,
  `Nombre Encargado` VARCHAR(45) NOT NULL,
  `Identidad Encargado` INT NOT NULL,
  `Celular` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Lugar de trabajo` VARCHAR(45) NOT NULL,
  `Ocupacion` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo-Encargado`),
  UNIQUE INDEX `Codigo-Encargado_UNIQUE` (`Codigo-Encargado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Traslados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Traslados` (
  `Codigo-Traslados` INT NOT NULL,
  `Nombre del estudiante` VARCHAR(45) NOT NULL,
  `Nombre del encargado` VARCHAR(45) NOT NULL,
  `Constancia de conducta` VARCHAR(45) NOT NULL,
  `Instituto del que se traslada` VARCHAR(45) NOT NULL,
  `Razon de traslado` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  UNIQUE INDEX `Codigo-Traslado_UNIQUE` (`Codigo-Traslados` ASC),
  PRIMARY KEY (`Codigo-Traslados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Matricula/traslados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Matricula/traslados` (
  `Codigo-Matricula/traslados` INT NOT NULL,
  `Codigo-Matriculas` INT NOT NULL,
  `Codigo-Encargado` INT NOT NULL,
  `Codigo-Traslados` INT NOT NULL,
  PRIMARY KEY (`Codigo-Matricula/traslados`),
  UNIQUE INDEX `Codigo-Matricula/traslados_UNIQUE` (`Codigo-Matricula/traslados` ASC),
  INDEX `fk_tbl-Matricula/traslados_tbl-matriculas1_idx` (`Codigo-Matriculas` ASC),
  INDEX `fk_tbl-Matricula/traslados_tbl-Encargado1_idx` (`Codigo-Encargado` ASC),
  INDEX `fk_tbl-Matricula/traslados_tbl-Traslados1_idx` (`Codigo-Traslados` ASC),
  CONSTRAINT `fk_tbl-Matricula/traslados_tbl-matriculas1`
    FOREIGN KEY (`Codigo-Matriculas`)
    REFERENCES `db-colegio`.`tbl-matriculas` (`Codigo-Matriculas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Matricula/traslados_tbl-Encargado1`
    FOREIGN KEY (`Codigo-Encargado`)
    REFERENCES `db-colegio`.`tbl-Encargado` (`Codigo-Encargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Matricula/traslados_tbl-Traslados1`
    FOREIGN KEY (`Codigo-Traslados`)
    REFERENCES `db-colegio`.`tbl-Traslados` (`Codigo-Traslados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Reportes/Excusas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Reportes/Excusas` (
  `Codigo-Reportes/Excusas` INT NOT NULL,
  PRIMARY KEY (`Codigo-Reportes/Excusas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Expulsiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Expulsiones` (
  `Codigo-Expulsiones` INT NOT NULL,
  UNIQUE INDEX `Codigo-Expulsiones_UNIQUE` (`Codigo-Expulsiones` ASC),
  PRIMARY KEY (`Codigo-Expulsiones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-ExtensionTitulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-ExtensionTitulos` (
  `Codigo-ExtensionTitulos` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Numero de Titulo` INT NOT NULL,
  `Promocion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo-ExtensionTitulos`),
  UNIQUE INDEX `Codigo-ExtensionTitulos_UNIQUE` (`Codigo-ExtensionTitulos` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Alumnos` (
  `Codigo-Alumnos` INT NOT NULL,
  `Extensiones de titulos` CHAR(45) NOT NULL,
  `Codigo-Matricula/traslados` INT NOT NULL,
  `Codigo-Reportes/Excusas` INT NOT NULL,
  `Codigo-Expulsiones` INT NOT NULL,
  `Codigo-ExtensionTitulos` INT NOT NULL,
  PRIMARY KEY (`Codigo-Alumnos`),
  UNIQUE INDEX `idtbl-_UNIQUE` (`Codigo-Alumnos` ASC),
  INDEX `fk_tbl-Alumnos_tbl-Matricula/traslados1_idx` (`Codigo-Matricula/traslados` ASC),
  INDEX `fk_tbl-Alumnos_tbl-Reportes/Excusas1_idx` (`Codigo-Reportes/Excusas` ASC),
  INDEX `fk_tbl-Alumnos_tbl-Expulsiones1_idx` (`Codigo-Expulsiones` ASC),
  INDEX `fk_tbl-Alumnos_tbl-ExtensionTitulos1_idx` (`Codigo-ExtensionTitulos` ASC),
  CONSTRAINT `fk_tbl-Alumnos_tbl-Matricula/traslados1`
    FOREIGN KEY (`Codigo-Matricula/traslados`)
    REFERENCES `db-colegio`.`tbl-Matricula/traslados` (`Codigo-Matricula/traslados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Alumnos_tbl-Reportes/Excusas1`
    FOREIGN KEY (`Codigo-Reportes/Excusas`)
    REFERENCES `db-colegio`.`tbl-Reportes/Excusas` (`Codigo-Reportes/Excusas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Alumnos_tbl-Expulsiones1`
    FOREIGN KEY (`Codigo-Expulsiones`)
    REFERENCES `db-colegio`.`tbl-Expulsiones` (`Codigo-Expulsiones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Alumnos_tbl-ExtensionTitulos1`
    FOREIGN KEY (`Codigo-ExtensionTitulos`)
    REFERENCES `db-colegio`.`tbl-ExtensionTitulos` (`Codigo-ExtensionTitulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Docentes` (
  `Codigo-Docentes` INT NOT NULL,
  `Codigo-IngresoCalificaciones` INT NOT NULL,
  PRIMARY KEY (`Codigo-Docentes`),
  INDEX `fk_tbl-Docentes_tbl-IngresoCalificaciones1_idx` (`Codigo-IngresoCalificaciones` ASC),
  CONSTRAINT `fk_tbl-Docentes_tbl-IngresoCalificaciones1`
    FOREIGN KEY (`Codigo-IngresoCalificaciones`)
    REFERENCES `db-colegio`.`tbl-IngresoCalificaciones` (`Codigo-IngresoCalificaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Aseo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Aseo` (
  `Codigo-Aseo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Identidad` VARCHAR(45) NOT NULL,
  `Genrro` VARCHAR(45) NOT NULL,
  `Distribucion de aseo` VARCHAR(45) NOT NULL,
  `Edificio Asignado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo-Aseo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Mantenimiento` (
  `Codigo-Mantenimiento` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Identidad` INT NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Turnos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo-Mantenimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Seguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Seguridad` (
  `Codigo-Seguridad` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Identidad` INT NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Area de trabajo` VARCHAR(45) NOT NULL,
  `Edificio Asignado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo-Seguridad`),
  UNIQUE INDEX `Codigo-Seguridad_UNIQUE` (`Codigo-Seguridad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Transporte` (
  `Codigo-Transporte` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Identidad` INT NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Turnos` VARCHAR(45) NOT NULL,
  `Vehiculo Asignado` VARCHAR(45) NOT NULL,
  `Ruta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo-Transporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl- Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl- Personal` (
  `Codigo- Personal` INT NOT NULL,
  `Codigo-Docentes` VARCHAR(6) NOT NULL,
  `Codigo-Aseo` INT NOT NULL,
  `Codigo-Mantenimiento` INT NOT NULL,
  `Codigo-Seguridad` INT NOT NULL,
  `Codigo-Transporte` INT NOT NULL,
  PRIMARY KEY (`Codigo- Personal`),
  UNIQUE INDEX `id- Personal_UNIQUE` (`Codigo- Personal` ASC),
  INDEX `fk_tbl- Personal_tbl-Docentes1_idx` (`Codigo-Docentes` ASC),
  INDEX `fk_tbl- Personal_tbl-Aseo1_idx` (`Codigo-Aseo` ASC),
  INDEX `fk_tbl- Personal_tbl-Mantenimiento1_idx` (`Codigo-Mantenimiento` ASC),
  INDEX `fk_tbl- Personal_tbl-Seguridad1_idx` (`Codigo-Seguridad` ASC),
  INDEX `fk_tbl- Personal_tbl-Transporte1_idx` (`Codigo-Transporte` ASC),
  CONSTRAINT `fk_tbl- Personal_tbl-Docentes1`
    FOREIGN KEY (`Codigo-Docentes`)
    REFERENCES `db-colegio`.`tbl-Docentes` (`Codigo-Docentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl- Personal_tbl-Aseo1`
    FOREIGN KEY (`Codigo-Aseo`)
    REFERENCES `db-colegio`.`tbl-Aseo` (`Codigo-Aseo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl- Personal_tbl-Mantenimiento1`
    FOREIGN KEY (`Codigo-Mantenimiento`)
    REFERENCES `db-colegio`.`tbl-Mantenimiento` (`Codigo-Mantenimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl- Personal_tbl-Seguridad1`
    FOREIGN KEY (`Codigo-Seguridad`)
    REFERENCES `db-colegio`.`tbl-Seguridad` (`Codigo-Seguridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl- Personal_tbl-Transporte1`
    FOREIGN KEY (`Codigo-Transporte`)
    REFERENCES `db-colegio`.`tbl-Transporte` (`Codigo-Transporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Secretaria` (
  `Codigo-Secretaria` INT NOT NULL,
  `Instituto` CHAR(45) NOT NULL,
  `Codigo-Alumnos` INT NOT NULL,
  `Codigo- Personal` INT NOT NULL,
  UNIQUE INDEX `id-Secretaria_UNIQUE` (`Codigo-Secretaria` ASC),
  PRIMARY KEY (`Codigo-Secretaria`),
  INDEX `fk_tbl-Secretaria_tbl-Alumnos1_idx` (`Codigo-Alumnos` ASC),
  INDEX `fk_tbl-Secretaria_tbl- Personal1_idx` (`Codigo- Personal` ASC),
  CONSTRAINT `fk_tbl-Secretaria_tbl-Alumnos1`
    FOREIGN KEY (`Codigo-Alumnos`)
    REFERENCES `db-colegio`.`tbl-Alumnos` (`Codigo-Alumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Secretaria_tbl- Personal1`
    FOREIGN KEY (`Codigo- Personal`)
    REFERENCES `db-colegio`.`tbl- Personal` (`Codigo- Personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`Inserciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`Inserciones` (
  `Codigo-Inserciones` INT NOT NULL,
  `Curso` VARCHAR(45) NOT NULL,
  `Asignatura` VARCHAR(45) NOT NULL,
  `Seccion` INT NOT NULL,
  PRIMARY KEY (`Codigo-Inserciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Inventario` (
  `Codigo-Inventario` INT NOT NULL,
  `Material Didactico` VARCHAR(45) NOT NULL,
  `Inmuebles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo-Inventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Instituto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Instituto` (
  `Codigo-Instituto` INT NOT NULL,
  `Codigo-Inserciones` INT NOT NULL,
  `Codigo-Inventario` INT NOT NULL,
  PRIMARY KEY (`Codigo-Instituto`),
  UNIQUE INDEX `id-Instituto_UNIQUE` (`Codigo-Instituto` ASC),
  INDEX `fk_tbl-Instituto_Inserciones1_idx` (`Codigo-Inserciones` ASC),
  INDEX `fk_tbl-Instituto_tbl-Inventario1_idx` (`Codigo-Inventario` ASC),
  CONSTRAINT `fk_tbl-Instituto_Inserciones1`
    FOREIGN KEY (`Codigo-Inserciones`)
    REFERENCES `db-colegio`.`Inserciones` (`Codigo-Inserciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Instituto_tbl-Inventario1`
    FOREIGN KEY (`Codigo-Inventario`)
    REFERENCES `db-colegio`.`tbl-Inventario` (`Codigo-Inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-PagosMatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-PagosMatricula` (
  `Codigo-PagosMatricula` INT NOT NULL,
  `Nombre Alumno` VARCHAR(45) NOT NULL,
  `Curso` VARCHAR(45) NOT NULL,
  `Fecha` INT NOT NULL,
  `Monto` INT NOT NULL,
  PRIMARY KEY (`Codigo-PagosMatricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Alumnado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Alumnado` (
  `Codigo-Alumnado` INT NOT NULL,
  `Pagos Mensualidades` VARCHAR(45) NOT NULL,
  `Otros pagos` VARCHAR(45) NOT NULL,
  `Codigo-PagosMatricula` INT NOT NULL,
  PRIMARY KEY (`Codigo-Alumnado`),
  INDEX `fk_tbl-Alumnado_tbl-PagosMatricula1_idx` (`Codigo-PagosMatricula` ASC),
  CONSTRAINT `fk_tbl-Alumnado_tbl-PagosMatricula1`
    FOREIGN KEY (`Codigo-PagosMatricula`)
    REFERENCES `db-colegio`.`tbl-PagosMatricula` (`Codigo-PagosMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Tesoreria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Tesoreria` (
  `Codigo-Tesoreria` INT NOT NULL,
  `Cuentas` CHAR(45) NOT NULL,
  `Codigo-Instituto` INT NOT NULL,
  `Codigo-Alumnado` INT NOT NULL,
  PRIMARY KEY (`Codigo-Tesoreria`),
  UNIQUE INDEX `id-Tesoreria_UNIQUE` (`Codigo-Tesoreria` ASC),
  INDEX `fk_tbl-Tesoreria_tbl-Instituto1_idx` (`Codigo-Instituto` ASC),
  INDEX `fk_tbl-Tesoreria_tbl-Alumnado1_idx` (`Codigo-Alumnado` ASC),
  CONSTRAINT `fk_tbl-Tesoreria_tbl-Instituto1`
    FOREIGN KEY (`Codigo-Instituto`)
    REFERENCES `db-colegio`.`tbl-Instituto` (`Codigo-Instituto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Tesoreria_tbl-Alumnado1`
    FOREIGN KEY (`Codigo-Alumnado`)
    REFERENCES `db-colegio`.`tbl-Alumnado` (`Codigo-Alumnado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Administracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Administracion` (
  `id-Administracion` INT NOT NULL,
  `Cuentas` CHAR(45) NOT NULL,
  `Codigo-Secretaria` INT NOT NULL,
  `Codigo-Tesoreria` INT NOT NULL,
  UNIQUE INDEX `id-Administracion_UNIQUE` (`id-Administracion` ASC),
  PRIMARY KEY (`id-Administracion`),
  INDEX `fk_tbl-Administracion_tbl-Secretaria_idx` (`Codigo-Secretaria` ASC),
  INDEX `fk_tbl-Administracion_tbl-Tesoreria1_idx` (`Codigo-Tesoreria` ASC),
  CONSTRAINT `fk_tbl-Administracion_tbl-Secretaria`
    FOREIGN KEY (`Codigo-Secretaria`)
    REFERENCES `db-colegio`.`tbl-Secretaria` (`Codigo-Secretaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl-Administracion_tbl-Tesoreria1`
    FOREIGN KEY (`Codigo-Tesoreria`)
    REFERENCES `db-colegio`.`tbl-Tesoreria` (`Codigo-Tesoreria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-IngresoCalificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-IngresoCalificaciones` (
  `Codigo-IngresoCalificaciones` INT NOT NULL,
  `Nombre estudiante` VARCHAR(45) NOT NULL,
  `Asignatura` VARCHAR(45) NOT NULL,
  `Numero de examen` INT NOT NULL,
  `Numer de acumulativo` INT NOT NULL,
  `Nombre docente` VARCHAR(45) NOT NULL,
  `Parcial` INT NOT NULL,
  `Nota examen` INT NOT NULL,
  `nota acumulativo` INT NOT NULL,
  `Total examenes` INT NOT NULL,
  `Total acumulativo` INT NOT NULL,
  `Promedio parcial` INT NOT NULL,
  `Nota Asignatura` INT NOT NULL,
  `Promedio final` INT NOT NULL,
  PRIMARY KEY (`Codigo-IngresoCalificaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-colegio`.`tbl-Docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-colegio`.`tbl-Docentes` (
  `Codigo-Docentes` INT NOT NULL,
  `Codigo-IngresoCalificaciones` INT NOT NULL,
  PRIMARY KEY (`Codigo-Docentes`),
  INDEX `fk_tbl-Docentes_tbl-IngresoCalificaciones1_idx` (`Codigo-IngresoCalificaciones` ASC),
  CONSTRAINT `fk_tbl-Docentes_tbl-IngresoCalificaciones1`
    FOREIGN KEY (`Codigo-IngresoCalificaciones`)
    REFERENCES `db-colegio`.`tbl-IngresoCalificaciones` (`Codigo-IngresoCalificaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
